spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polling_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&jdbcCompliantTruncation=false
    username: nguyennghang
    password: nguyennghang00